export const UserActionTypes = {
  SET_CURRENT_USER_TYPE: "SET_CURRENT_USER_TYPE",
  SET_CURRENT_USER_ID: "SET_CURRENT_USER_ID",
};

export const ApplicationActionTypes = {
  MAKE_APPLICATION: 'MAKE_APPLICATION',
  GET_ALL_APPLICATIONS: 'GET_ALL_APPLICATIONS',
  SET_CURRENT_FILE: 'SET_CURRENT_FILE',
}

export const AdminActionTypes = {
  SET_CURRENT_ADMIN_ID: 'SET_CURRENT_ADMIN_ID',
  SET_CURRENT_ADMIN_TYPE: 'SET_CURRENT_ADMIN_TYPE',
  GET_ALL_IITISM_APPLICATIONS: 'GET_ALL_IITISM_APPLICATIONS',
  GET_ALL_EXTERNAL_APPLICATIONS: 'GET_ALL_EXTERNAL_APPLICATIONS',
  SET_CURRENT_APPLICATION: 'SET_CURRENT_APPLICATION',
  SET_CURRENT_IDEA: 'SET_CURRENT_IDEA',
  SET_CURRENT_PDF: 'SET_CURRENT_PDF'
}

export const AlertActionTypes = {
  SET_ALERT_MESSAGE: "SET_ALERT_MESSAGE",
};

export const ErrorActionTypes = {
  GET_ERRORS: "GET_ERRORS",
};

export const EventActionTypes = {
  GET_UPCOMING_EVENTS: "GET_UPCOMING_EVENTS",
  GET_FLAGSHIP_EVENTS: "GET_FLAGSHIP_EVENTS",
  GET_FLAGSHIP_EVENT_CATEGORIES: "GET_FLAGSHIP_EVENT_CATEGORIES",
  GET_MIC_EVENTS: "GET_MIC_EVENTS",
  GET_OTHER_EVENTS: "GET_OTHER_EVENTS",
  GET_CURRENT_PHOTOS: "GET_CURRENT_PHOTOS",
  GET_ONGOING_EVENTS: "GET_ONGOING_EVENTS"
};

export const AnnouncementActionTypes = {
  GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS",
};

export const VideosActionTypes = {
  GET_YOUTUBE_VIDEOS: "GET_YOUTUBE_VIDEOS",
};
